[package]
name = "lexer"
version = "0.1.0"
authors = ["Ler Daddy <mielkedtyler@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
